FROM jupyter/scipy-notebook:281505737f8a

USER root

RUN apt-get update && \
    apt-get install -y curl gfortran openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN conda install --quiet --yes cling && \
    conda clean -tipsy

USER $NB_USER
